### ISSUE TITLE
Authentication with special characters not working 

### ISSUE THREAD

**Issue by Bird87ZA** [OpenXbox/xbox-webapi-python#13]
It seems like the api is changing special characters. If I run `xbox-authenticate` the below happens:

```
user:~$ xbox-authenticate --email test@example.com --password MyPass^!7*
xbox-authenticate --email test@example.com --password MyPass^-V
Email/Password authentication failed! Err: Could not log in with supplied credentials
```

What could be the cause? Or should I escape the password?

**Comment by BeLimitless** [comment]
Encode your password before doing the authentication.

**Comment by Bird87ZA** [comment]
Encode how? Just base64?

**Comment by Bird87ZA** [comment]
Tried Base64 and a urlencode and both still fail.

**Comment by BeLimitless** [comment]
Strange, I use url encode and mine is working. Unable to check my code until Sunday as I am on holiday.

**Comment by Bird87ZA** [comment]
No worries. I'll continue trying until I figure it out.

If I figure it out before Sunday, will post here. Perhaps something I'll add to the docs just so everyone knows :)

**Comment by Bird87ZA** [comment]
Just an update on this. I encode my password and get this: `MyPass%5E%217%2A`

Then I run: `xbox-authenticate --email test@example.com --password MyPass%5E%217%2A`

And it still throws:
`Email/Password authentication failed! Err: Could not log in with supplied credentials`

When I use a buddies login that has no special characters, it works 100% fine.

**Comment by tuxuser** [comment]
Try like this:
```
xbox-authenticate --email test@example.com --password "MyPass^!7*"
xbox-authenticate --email test@example.com --password 'MyPass^!7*'
```

**Comment by Bird87ZA** [comment]
Putting it in single apostrophes worked. Thanks
