### ISSUE TITLE
How to determine service config id (scid)?

### ISSUE THREAD

**Issue by stepthom** [OpenXbox/xbox-webapi-python#18]
In order to call the `userstats.get_stats()` method, we need to pass in a service_config_id string. How can we figure out what this should be? For example, for the game "Halo MCC"?

**Comment by pacMakaveli** [comment]
When you get a User's achievements/games, in the response you should have a `serviceConfigId`.
```{"lastUnlock"=>"2015-04-19T13:48:26.8706895Z", "titleId"=>1144039928, "serviceConfigId"=>"77290100-225e-4768-9373-98164430a9f8", "titleType"=>"Game", "platform"=>"XboxOne", "name"=>"Halo: The Master Chief Collection", "earnedAchievements"=>6, "currentGamerscore"=>40, "maxGamerscore"=>7000}```
