### ISSUE TITLE
The token file isn't created

### ISSUE THREAD

**Issue by Gurrman375** [OpenXbox/xbox-webapi-python#20]
When running the command "xbox-authenticate --tokens tokens.json --email ..." looking at the directory AppData\Local\OpenXbox\xbox there is no tokens.json file.

![image](https://user-images.githubusercontent.com/25113575/79060883-f3e66280-7c3e-11ea-8457-0f0b38b3d22c.png)
()

**Comment by tuxuser** [comment]
Well, have a look in C:\Windows\System32 - there should be tokens.json.

The script will use the path you provide via `--tokens` -> you passed a filepath relative to your current directory -> `C:\Windows\System32\tokens.json`

If you **don't** pass the argument, the standard directory is assumed -> `C:\Users\<user>\AppData\Local\OpenXbox\xbox`
