### ISSUE TITLE
Xbox 2FA options mixed up

### ISSUE THREAD

**Issue by mike391** [OpenXbox/xbox-webapi-python#21]
When authenticating via 2FA:

Choose desired entry:
  0: TwoFactorAuthMethods.Email, Name: *******@gmail.com
  1: TwoFactorAuthMethods.Email, Name: *****@gmail.com
  2: TwoFactorAuthMethods.SMS, Name: ********00
  3: TwoFactorAuthMethods.TOTPAuthenticator, Name: Authenticator app
  4: TwoFactorAuthMethods.TOTPAuthenticatorV2, Name: 9999999999999

Selecting option 3, asks for approval in the authenticator app on your phone but the CLI is waiting for a 2FA code, entering a 2FA code ends in error.

Option 4 triggers approval in authenticator app on your phone and clicking approve works as expected

**Comment by tuxuser** [comment]
TOTPAuthenticator (v1) is OTP code - its the *legacy* Microsoft Authenticator app (or third-party app)
TOTPAuthenticator v2 is the push-based Microsoft Authenticator app.

It might be the case that your option 3 (TwoFactorAuthMethods.TOTPAuthenticator, Name: Authenticator app) refers to a previously paired Authenticator app, thats why the code you get from yout Microsoft Authenticator app does not work.

Hope you understand what I mean.
