### ISSUE TITLE
XboxLiveClient.message.send_message function does not work

### ISSUE THREAD

**Issue by naveenailawadi** [OpenXbox/xbox-webapi-python#22]
`response = self.xbl_client.message.send_message("This is a test", gamertags="['some', 'gamertags']")`

When sending a message, no error is thrown. Instead, I receive the following 400 response: {"errorCode":1001,"errorMessage":"Failed to deserialize request."}.

**Comment by tuxuser** [comment]
New messaging endpoint is implemented in v2
