### ISSUE TITLE
Setup login with Xbox Live

### ISSUE THREAD

**Issue by MKBSoftware** [OpenXbox/xbox-webapi-python#24]
Is there anybody that can assist me in setting up sign in with Xbox live flow so I can have people signing with their Xbox live account? And to get the proper tokens (xsts and uhs).

I searched many resources, but somehow, I am unable to get this working.

**Comment by Gurrman375** [comment]
Check out this link: https://github.com/OpenXbox/xbox-webapi-python/blob/master/xbox/webapi/scripts/authenticate.py
Also try using this command:
`xbox-authenticate --tokens tokens.json --email no@live.com --password abc123`

**Comment by tuxuser** [comment]
https://gist.github.com/tuxuser/8b7cc153cdecd0a9c3f2694850fa90bd
