### ISSUE TITLE
RequestSigner: MaxBodyBytes not used?

### ISSUE THREAD

**Issue by Alexis-Bize** [OpenXbox/xbox-webapi-python#33]
Hey there, as NSAL services return a `MaxBodyBytes` property depending of the used `Version` from `Policies`, shouldn't it be used to truncate the `body` (if required) in the `_hash` method?

**Comment by tuxuser** [comment]
Absolutely correct.
But as we neither have a parser for NSAL endpoints response nor is the RequestSigner actually utilized right now, it is not implemented yet.

**Comment by Alexis-Bize** [comment]
Oh, great then. Looking forward to it!

**Comment by Alexis-Bize** [comment]
Note: I've manage to create a valid `Signature` with the returned `MaxBodyBytes` from https://title.mgt.xboxlive.com/titles/default/endpoints?type=1 in my NodeJS implementation. As the values doesn't seem to change, I've stored them in a constant at the moment.

```
// @see https://title.mgt.xboxlive.com/titles/default/endpoints?type=1
const NSALSignaturePolicies = [
	{ Version: 1, MaxBodyBytes: 8192 },
	{ Version: 1, MaxBodyBytes: 4294967295 }
];
```

Body payload:
```javascript
{
    "RelyingParty":"http://auth.xboxlive.com",
    "TokenType":"JWT",
    "Properties":{
        "AuthMethod":"ProofOfPossession",
        "Id":"A29BDCC5-F466-4EDC-BA75-06131C95B4D3", // Generated on the fly
        "DeviceType":"iOS",
        "Version":"13.3.1",
        "ProofKey":{
            "crv":"P-256",
            "alg":"ES256",
            "use":"sig",
            "kty":"EC",
            "x":"xnLPe2vvqSjhIx0d1MUxi5rc8xFM4bz4xS-_0hCtQEs",
            "y":"tDlPYugl5KOzjxJXRVf1jYpLrcZ6HUr-Znz7TMetQy8"
        }
    }
}
```

Output signature:
```
AAAAAQHWsHB870aQLWaQZe4laRe6UHPOx7htFwxlZ5+7hzOHjOYRmASq+di+hH9Lg2O15BO7t0jiBnHQr4yfew6oneO1xUvLa8QGvw==
```
