### ISSUE TITLE
Gamestats "stats_fields"

### ISSUE THREAD

**Issue by BeLimitless** [OpenXbox/xbox-webapi-python#4]
The gamestats batch feature is working great, but I am missing data, I am trying to figure out the "stats_field" params to get "MinutesPlayed" for a game.

`post_data = {
            'arrangebyfield': 'xuid',
            'groups': [
                {
                    'name': 'Hero',
                    'titleId': int(title_id)
                }
            ],
            'stats': [dict(name=stat, titleId=int(title_id)) for stat in stats_fields],
            'xuids': [str(xid) for xid in xuids]
        }`

**Comment by tuxuser** [comment]
Just use https://github.com/OpenXbox/xbox-webapi-python/commit/eb417533658dca23e130e9ffb2ff56c22ae88b92#diff-7577e603200d42ab26c03471a0120ebdR13
by title id ;) It just returns the single field "MinutesPlayed" .. but thats what you want, right ?

for batch it does not respect the requested field for whatever reason.

**Comment by tuxuser** [comment]
Can I close this issue? Got it solved?

**Comment by BeLimitless** [comment]
Sorry for the late response, this is solved.
