### ISSUE TITLE
Authentication Script Stuck in Loop

### ISSUE THREAD

**Issue by bsled96** [OpenXbox/xbox-webapi-python#48]
So I was able to authenticate on my Mac, but I am now trying to authenticate on my Linux server and it gets stuck in an infinite loop. It looks like it's getting stuck on:

`async_main(args.client_id, args.client_secret, args.redirect_uri, args.tokens)`

This seems to happen to both of my Linux systems, so I don't think it's a problem on my end. This happens whether I use the xbox-authenticate option in command line or if I use the Python script. I'm running Ubuntu 18. I run either the command or the script and it just gets stuck there. It never times out and it returns no errors.

**Comment by bsled96** [comment]
I had to copy my tokens from my Mac to my Ubuntu machine. Not sure why the auth scripts provided did not run as intended on their own. But it's working now.

**Comment by tuxuser** [comment]
The authenticate script opens a local socket.. which means the actual authentication needs to happen on the same machine, so the callback can reach the http server daemon
