### ISSUE TITLE
[Question] Is there a way to find out which users that you are currently in a party with?

### ISSUE THREAD

**Issue by johnsturgeon** [OpenXbox/xbox-webapi-python#65]

**Comment by tuxuser** [comment]
No

**Comment by johnsturgeon** [comment]
OK, thanks.  I will take a look at `OpenXBL`  The seem to provide a REST interface for that.

**Comment by Gurrman375** [comment]
@johnsturgeon your not gonna really get anything out of OpenXBL because they haven't finished working on /party endpoint.

**Comment by johnsturgeon** [comment]
You are correct!  I tried it out yesterday evening and .. nothing.
