### ISSUE TITLE
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://login.live.com/oauth20_token.srf')

### ISSUE THREAD

**Issue by begyy** [OpenXbox/xbox-webapi-python#70]
![image](https://user-images.githubusercontent.com/44405438/139422774-7231ebe1-2034-411d-8480-20d6f2afdf6d.png)

**Comment by Lakrix** [comment]
Hey, did u manage to solve this?

**Comment by mason1171** [comment]
@Lakrix @begyy 
Any luck?

**Comment by paulithan** [comment]
@Lakrix @mason1171 @begyy Anyone manage to get past this?
