### ISSUE TITLE
Failed to run authentication command

### ISSUE THREAD

**Issue by Lakrix** [OpenXbox/xbox-webapi-python#74]
Hey, Im not sure what Im doing wrong. After generating the client secret and client Id I tried to authenticate. 
`xbox-authenticate --client-id <client-id> --client-secret <client-secret>`
I get the following error
![Screenshot 2022-03-28 at 18 12 53](https://user-images.githubusercontent.com/7085072/160441718-0c4fff06-250e-4a43-92cb-fb59eac6d2ca.png)
Any help is appreciated.

**Comment by austensatterlee** [comment]
Any updates on what the issue was? Currently debugging an issue with this exact response, and I'm trying to figure out how an account gets into a state that causes this.
