### ISSUE TITLE
how to verify the user have my program ownership?

### ISSUE THREAD

**Issue by molixiaoge** [OpenXbox/xbox-webapi-python#8]
I read all the xbox document,but i can not find how to check the user whether  have my game's ownership.I want to check the ownership at my server side,but i do not know the way.

Thanks.

**Comment by tuxuser** [comment]
Not possible

**Comment by molixiaoge** [comment]
The xbox only have client's api? So,if i have  recharge or buy game item,i can not check anything on my game's server side？
Thx.

**Comment by tuxuser** [comment]
There are server sided things you can use, sure, but it's out-of-scope for this project.

Xbox Live Creators program or something along those lines might be better suited for your question.

**Comment by molixiaoge** [comment]
Thx ,for your reply.
I have do the steam game's recharge,which's document so easy and clearly.
But with xbox's documnet ,i have lost myself.It is heavily complex.I can not find it.
