### ISSUE TITLE
How to get Game Title ID

### ISSUE THREAD

**Issue by cdangerdouglas** [OpenXbox/xbox-webapi-python#9]
title says it all. how may i obtain a xbox one game's title id? for example, if i want the title id of halo 5 so that i may use this api to see all the halo 5 community clips?

**Comment by bensonlee311** [comment]
I also want to know if there is any web api to get title id ?thanks

**Comment by tuxuser** [comment]
EDS should work for that matter

**Comment by cdangerdouglas** [comment]
What is EDS?

**Comment by tuxuser** [comment]
xbox_client.eds endpoint, Entertainment discovery services
